### ISSUE TITLE
7회차 (마무리)

### ISSUE THREAD

**Issue by ggyu0629** [IMS-STUDY/Java-Study#14]
## 목표
자바의 Input과 Ontput에 대해 학습하세요.

### 학습할 것 (필수)
\- 스트림 (Stream) / 버퍼 (Buffer) / 채널 (Channel) 기반의 I/O
\- InputStream과 OutputStream
\- Byte와 Character 스트림
\- 표준 스트림 (System.in, System.out, System.err)
\- 파일 읽고 쓰기

## 목표
자바의 제네릭에 대해 학습하세요.

### 학습할 것 (필수)
\- 제네릭 사용법
\- 제네릭 주요 개념 (바운디드 타입, 와일드 카드)
\- 제네릭 메소드 만들기
\- Erasure

## 목표
자바의 람다식에 대해 학습하세요.

### 학습할 것 (필수)
\- 람다식 사용법
\- 함수형 인터페이스
\- Variable Capture
\- 메소드, 생성자 레퍼런스

## 마감일시
23-11-19 자정

**Comment by yyechan0602** [comment]
https://yyechan0602.github.io/java/IO/
https://yyechan0602.github.io/java/Generic/
https://yyechan0602.github.io/java/Lambda/

**Comment by bnh5992** [comment]
https://bnh4924.tistory.com/58
https://bnh4924.tistory.com/59
https://bnh4924.tistory.com/60

**Comment by ggyu0629** [comment]
https://qrazy-every-day.tistory.com/74
https://qrazy-every-day.tistory.com/75
https://qrazy-every-day.tistory.com/76

**Comment by JoEunSang** [comment]
https://codehouse0224.tistory.com/62
https://codehouse0224.tistory.com/63
https://codehouse0224.tistory.com/64

**Comment by bluewing0303** [comment]
https://qwerty0419.tistory.com/39
https://qwerty0419.tistory.com/40
https://qwerty0419.tistory.com/41

**Comment by dlwhdwo37** [comment]
https://jedge11.tistory.com/14
https://jedge11.tistory.com/15
https://jedge11.tistory.com/16
